---
title: "Lab Excercise 1"
author: "Bagilidad Ace"
date: "2024-02-08"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 Product 1 Tshirts 100 Products
```{r}
#install.packages(rvest)
#install.packages(dplyr)
#install.packages(polite)
#install.packages(tidyverse)


library(rvest)
library(dplyr)
library(polite)
library(tidyverse)


#Mens Caps
urlName1 <- "https://www.amazon.com.au/Mens-Hats-Caps-Accessories/s?keywords=Men%27s+Hats+%26+Caps&rh=n%3A5130942051%2Cp_n_free_shipping_eligible%3A5363790051&c=ts&ts_id=5130942051"

session <- bow(urlName1, user_agent = "For Educational Purposes")
session


amazonPage <- read_html(urlName1)

Sys.sleep(10)

category1 <- "Mens Hats and Caps"

#name
Name_1 <- scrape(session) %>%
  html_nodes("span.a-text-normal") %>%
  html_text



#price1
Price_1 <- scrape(session) %>%
  html_nodes("span.a-offscreen") %>%
  html_text


#ratings
Ratings_1 <- scrape(session) %>%
  html_nodes("span.a-icon-alt") %>%
  html_text



#Total number of reviews
NumRev_1 <- scrape(session) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text



#2nd page
urlName2 <- "https://www.amazon.com.au/Mens-Hats-Caps-Accessories/s?k=Men%27s+Hats+%26+Caps&page=2&c=ts&qid=1708140933&ts_id=5130942051&ref=sr_pg_2"
session2 <- bow(urlName2, user_agent = "For Educational Purposes")
session2

Sys.sleep(10)

Name_2 <- scrape(session2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text


#price2
Price_2 <- scrape(session2) %>%
  html_nodes("span.a-offscreen") %>%
  html_text


#Ratings
Ratings_2 <- scrape(session2) %>%
  html_nodes("span.a-icon-alt") %>%
  html_text


#Number of Ratings 
NumRev_2 <- scrape(session) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text



#3rd page

urlName3 <- "https://www.amazon.com.au/Mens-Hats-Caps-Accessories/s?k=Men%27s+Hats+%26+Caps&page=3&c=ts&qid=1708141481&ts_id=5130942051&ref=sr_pg_3"

session3 <- bow(urlName3, user_agent = "For Educational Purposes")
session3

Sys.sleep(10)

#name
Name_3 <- scrape(session3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text



#price
Price_3 <- scrape(session3) %>%
  html_nodes("span.a-offscreen") %>%
  html_text



#Ratings
Ratings_3 <- scrape(session3) %>%
  html_nodes("span.a-icon-alt") %>%
  html_text


#Number of Ratings 
NumRev_3 <- scrape(session3) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text




#mensHatsandCaps DataFrame 


mensHatsandCaps_pagedf1 <- data.frame(Category = rep(category1,each=47),
                      Name = Name_1[2:48],
                      Price = Price_1[1:47],
                      Rating = Ratings_1[1:47],
                      Number.of.Reviews = NumRev_1[1:47]
                      )


mensHatsandCaps_pagedf2 <- data.frame(Category = rep(category1,each=47),
                      Name = Name_2[2:48],
                      Price = Price_2[1:47],
                      Rating = Ratings_2[1:47],
                      Number.of.Reviews = NumRev_2[1:47]
                      )



mensHatsandCaps_pagedf3 <- data.frame(Category = rep(category1,each=6),
                      Name = Name_3[2:7],
                      Price = Price_3[1:6],
                      Rating = Ratings_3[1:6],
                      Number.of.Reviews = NumRev_3[1:6]
                      
                      
                       )


mensHatsandCaps <- rbind(mensHatsandCaps_pagedf1,mensHatsandCaps_pagedf2,mensHatsandCaps_pagedf3)
             
#view(mensHatsandCaps)



```


Product 2 Mens Shorts 100 products


```{r}
#Mens Shorts
url1 <- "https://www.amazon.co.uk/b?node=1731002031&ref=sr_pg_1"

session <- bow(url1, user_agent = "For Educational Purposes")



amazonPage <- read_html(url1)

Sys.sleep(10)

category2 <- "Mens Shorts"
#name1
Name1 <- scrape(session) %>%
  html_nodes("span.a-text-normal") %>%
  html_text



#price1
Price1 <- scrape(session) %>%
  html_nodes("span.a-offscreen") %>%
  html_text


#ratings
Ratings1 <- scrape(session) %>%
  html_nodes("span.a-icon-alt") %>%
  html_text


#Total number of reviews
NumRev1 <- scrape(session) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text


#2nd page
url2 <- "https://www.amazon.co.uk/s?k=Men%27s+Shorts&i=fashion-mens-clothing&rh=n%3A1731002031&page=2&c=ts&qid=1708143613&ts_id=1731002031&ref=sr_pg_2"
session_2 <- bow(url2, user_agent = "For Educational Purposes")

Sys.sleep(10)

Name2 <- scrape(session_2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text


#price2
Price2 <- scrape(session_2) %>%
  html_nodes("span.a-offscreen") %>%
  html_text


#Ratings
Ratings2 <- scrape(session_2) %>%
  html_nodes("span.a-icon-alt") %>%
  html_text



#Number of Ratings 
NumRev2 <- scrape(session_2) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text


#3rd page

url3 <- "https://www.amazon.co.uk/s?k=Men%27s+Shorts&i=fashion-mens-clothing&rh=n%3A1731002031&page=3&c=ts&qid=1708143800&ts_id=1731002031&ref=sr_pg_3"

session_3 <- bow(url3, user_agent = "For Educational Purposes")
session3

Sys.sleep(10)

#name
Name3 <- scrape(session_3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text


#price
Price3 <- scrape(session_3) %>%
  html_nodes("span.a-offscreen") %>%
  html_text


#Ratings
Ratings3 <- scrape(session_3) %>%
  html_nodes("span.a-icon-alt") %>%
  html_text


#Number of Ratings 
NumRev3 <- scrape(session_3) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text


#Viewing of page

pagedf1 <- data.frame(Category = rep(category2,each=47),
                      Name = Name1[2:48],
                      Price = Price1[1:47],
                      Rating = Ratings1[1:47],
                      Number.of.Reviews = NumRev1[1:47]
                      )


pagedf2 <- data.frame(Category = rep(category2,each=47),
                      Name = Name2[2:48],
                      Price = Price2[1:47],
                      Rating = Ratings2[1:47],
                      Number.of.Reviews = NumRev2[1:47]
                      )



pagedf3 <- data.frame(Category = rep(category2,each=6),
                      Name = Name3[2:7],
                      Price = Price3[1:6],
                      Rating = Ratings3[1:6],
                      Number.of.Reviews = NumRev3[1:6]
                      
                      
                       )



MenShorts <- rbind(pagedf1,pagedf2,pagedf3)
               
#view(MenShorts)


#Merging of two products

Products <- rbind(MenShorts,mensHatsandCaps)
Products
#view(Products)
```
################################################################################
10 PRODUCTS REVIEWS

PRODUCT 1
```{r}
# install.packages("httr")
# install.packages("rvest")

library(httr)
library(rvest)
library(selectr)

category <- "Mens Tshirt"

scrapingNodes <- function(session, HTMLnodes) {
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link) {
  session <- bow(link, user_agent = "For Educational Purpose")

  Sys.sleep(4) # Add a delay of 4 seconds

  Product <- scrapingNodes(session, "h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session, "span.a-profile-name")[3:11]
  prodReview <- scrapingNodes(session, "span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session, "span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session, "span.a-icon-alt")[4:12]

  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}


link1 <- "https://www.amazon.co.uk/Jack-Jones-Mens-Jjecorp-T-Shirt/product-reviews/B09W38Q4WX/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1 <- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/Jack-Jones-Mens-Jjecorp-T-Shirt/product-reviews/B09W38Q4WX/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2 <- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/JACK-JONES-12221269-Mens-T-Shirt/product-reviews/B0CTHXDTL5/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3 <- prodDetails(link3)

ProdReview1 <- rbind(page1, page2, page3)

#view(ProdReview1)

```

PRODUCT 2
```{r}

library(httr)
library(rvest)
library(selectr)
#2nd Product 



category <- "Mens Tshirt"

scrapingNodes <- function(session,HTMLnodes){
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link){
  session <- bow(link,user_agent = "For Educational Purpose")
  
  Sys.sleep(4)
   
  Product <- scrapingNodes(session,"h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session,"span.a-profile-name")[3:11]
  prodReview <- scrapingNodes(session,"span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session,"span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session,"span.a-icon-alt")[4:12]
  
  
  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}

#Link for the seperate pages.
link1 <- "https://www.amazon.co.uk/BOSS-Mens-Pack-Classic-T-Shirt/product-reviews/B0CPW6YST7/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1<- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/BOSS-Mens-Pack-Classic-T-Shirt/product-reviews/B0CPW6YST7/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2<- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/BOSS-Mens-Pack-Classic-T-Shirt/product-reviews/B0CPW6YST7/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3<- prodDetails(link3)

ProdReview2 <- rbind(page1,page2,page3)

# view(ProdReview2)

```

PRODUCT 3
```{r}

library(httr)
library(rvest)
library(selectr)
#3rd Product 



category <- "Mens Tshirt"

scrapingNodes <- function(session,HTMLnodes){
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link){
  session <- bow(link,user_agent = "For Educational Purpose")
  
  Sys.sleep(5)
   
  Product <- scrapingNodes(session,"h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session,"span.a-profile-name")[3:11]
  prodReview <- scrapingNodes(session,"span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session,"span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session,"span.a-icon-alt")[4:12]
  
  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}

#Link for the seperate pages.
link1 <- "https://www.amazon.co.uk/Fruit-Loom-Mens-Heavy-T-Shirt/product-reviews/B00UG7WDRK/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1<- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/Fruit-Loom-Mens-Heavy-T-Shirt/product-reviews/B00UG7WDRK/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2<- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/Fruit-Loom-Mens-Heavy-T-Shirt/product-reviews/B00UG7WDRK/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3<- prodDetails(link3)

ProdReview3 <- rbind(page1,page2,page3)

# view(ProdReview3)



```


PRODUCT 4
```{r}

library(httr)
library(rvest)
library(selectr)
#4th Product 



category <- "Mens Tshirt"

scrapingNodes <- function(session,HTMLnodes){
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link){
  session <- bow(link,user_agent = "For Educational Purpose")
  
  Sys.sleep(7)
   
  Product <- scrapingNodes(session,"h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session,"span.a-profile-name")[4:12]
  prodReview <- scrapingNodes(session,"span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session,"span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session,"span.a-icon-alt")[4:12]
  
  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}

#Link for the seperate pages.
link1 <- "https://www.amazon.co.uk/Amazon-Essentials-Short-Sleeve-Gingham-Button/product-reviews/B0775YFQMQ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1<- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/Amazon-Essentials-Short-Sleeve-Gingham-Button/product-reviews/B0775YFQMQ/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2<- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/Amazon-Essentials-Short-Sleeve-Gingham-Button/product-reviews/B0775YFQMQ/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3<- prodDetails(link3)

ProdReview4 <- rbind(page1,page2,page3)

# view(ProdReview4)



```


PRODUCT 5
```{r}

library(httr)
library(rvest)
library(selectr)
#5th Product 



category <- "Mens Tshirt"

scrapingNodes <- function(session,HTMLnodes){
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link){
  session <- bow(link,user_agent = "For Educational Purpose")
  
  Sys.sleep(6)
  
  Product <- scrapingNodes(session,"h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session,"span.a-profile-name")[3:11]
  prodReview <- scrapingNodes(session,"span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session,"span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session,"span.a-icon-alt")[4:12]
  
  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}

#Link for the seperate pages.
link1 <- "https://www.amazon.co.uk/Urban-Classics-Oversized-Sleeves-Shoulders/product-reviews/B0014679X0/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1<- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/Urban-Classics-Oversized-Sleeves-Shoulders/product-reviews/B0014679X0/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2<- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/Urban-Classics-Oversized-Sleeves-Shoulders/product-reviews/B0014679X0/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3<- prodDetails(link3)

ProdReview5 <- rbind(page1,page2,page3)

# view(ProdReview5)



```


PRODUCT 6
```{r}

library(httr)
library(rvest)
library(selectr)
#6th Product 



category <- "Mens Tshirt"

scrapingNodes <- function(session,HTMLnodes){
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link){
  session <- bow(link,user_agent = "For Educational Purpose")
 
  Sys.sleep(4) 
  Product <- scrapingNodes(session,"h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session,"span.a-profile-name")[3:11]
  prodReview <- scrapingNodes(session,"span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session,"span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session,"span.a-icon-alt")[4:12]
  
  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}

#Link for the seperate pages.
link1 <- "https://www.amazon.co.uk/Under-Armour-Sportstyle-Training-Fast-Drying/product-reviews/B0CTNDJMGQ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1<- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/Under-Armour-Sportstyle-Training-Fast-Drying/product-reviews/B0CTNDJMGQ/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2<- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/Under-Armour-Sportstyle-Training-Fast-Drying/product-reviews/B0CTNDJMGQ/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3<- prodDetails(link3)

ProdReview6 <- rbind(page1,page2,page3)

# view(ProdReview6)


```

PRODUCT 7
```{r}

library(httr)
library(rvest)
library(selectr)
#7th Product 



category <- "Mens Tshirt"

scrapingNodes <- function(session,HTMLnodes){
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link){
  session <- bow(link,user_agent = "For Educational Purpose")
  
  Sys.sleep(10)
  Product <- scrapingNodes(session,"h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session,"span.a-profile-name")[3:11]
  prodReview <- scrapingNodes(session,"span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session,"span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session,"span.a-icon-alt")[4:12]
  
  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}

#Link for the seperate pages.
link1 <- "https://www.amazon.co.uk/Tommy-Hilfiger-Mens-Logo-T-Shirt/product-reviews/B0CQMFVC38/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1<- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/Tommy-Hilfiger-Mens-Logo-T-Shirt/product-reviews/B0CQMFVC38/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2<- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/Tommy-Hilfiger-Mens-Logo-T-Shirt/product-reviews/B0CQMFVC38/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3<- prodDetails(link3)

ProdReview7 <- rbind(page1,page2,page3)

# view(ProdReview7)


```


PRODUCT 8
```{r}

library(httr)
library(rvest)
library(selectr)
#8th Product 



category <- "Mens Tshirt"

scrapingNodes <- function(session,HTMLnodes){
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link){
  session <- bow(link,user_agent = "For Educational Purpose")
  
  Sys.sleep(10)
  Product <- scrapingNodes(session,"h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session,"span.a-profile-name")[3:11]
  prodReview <- scrapingNodes(session,"span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session,"span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session,"span.a-icon-alt")[4:12]
  
  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}

#Link for the seperate pages.
link1 <- "https://www.amazon.co.uk/Champion-Classic-Jersey-Script-T-Shirt/product-reviews/B09T9Y5MMR/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1<- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/Champion-Classic-Jersey-Script-T-Shirt/product-reviews/B09T9Y5MMR/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2<- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/Champion-Classic-Jersey-Script-T-Shirt/product-reviews/B09T9Y5MMR/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3<- prodDetails(link3)

ProdReview8 <- rbind(page1,page2,page3)

# view(ProdReview8)


```

PRODUCT 9
```{r}

library(httr)
library(rvest)
library(selectr)
#9th Product 



category <- "Mens Tshirt"

scrapingNodes <- function(session,HTMLnodes){
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link){
  session <- bow(link,user_agent = "For Educational Purpose")
  
  Sys.sleep(10)
  Product <- scrapingNodes(session,"h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session,"span.a-profile-name")[3:11]
  prodReview <- scrapingNodes(session,"span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session,"span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session,"span.a-icon-alt")[4:12]
  
  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}

#Link for the seperate pages.
link1 <- "https://www.amazon.co.uk/Jack-Jones-Jjegingham-Twill-Shirt/product-reviews/B08BJQ3LPS/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1<- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/Jack-Jones-Jjegingham-Twill-Shirt/product-reviews/B08BJQ3LPS/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2<- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/Jack-Jones-Jjegingham-Twill-Shirt/product-reviews/B08BJQ3LPS/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3<- prodDetails(link3)

ProdReview9 <- rbind(page1,page2,page3)

# view(ProdReview9)


```


PRODUCT 10
```{r}

library(httr)
library(rvest)
library(selectr)
#10th Product 



category <- "Mens Tshirt"

scrapingNodes <- function(session,HTMLnodes){
  session %>% scrape() %>% html_nodes(HTMLnodes) %>% html_text()
}

prodDetails <- function(link){
  session <- bow(link,user_agent = "For Educational Purpose")
  
  Sys.sleep(10)
  Product <- scrapingNodes(session,"h1.a-size-large.a-text-ellipsis")
  prodReviewer <- scrapingNodes(session,"span.a-profile-name")[3:11]
  prodReview <- scrapingNodes(session,"span.a-size-base.review-text.review-text-content")[1:9]
  RevDate <- scrapingNodes(session,"span.a-size-base.a-color-secondary.review-date")[3:11]
  prodRatings <- scrapingNodes(session,"span.a-icon-alt")[4:12]
  
  TshirtProd <- data.frame(Category = category,
                           ProductName = Product,
                           Reviewer = prodReviewer,
                           Review = prodReview,
                           ReviewDate = RevDate,
                           Rating = prodRatings)
  return(TshirtProd)
}

#Link for the seperate pages.
link1 <- "https://www.amazon.co.uk/Levis-Original-Short-Sleeved-Housemark-T-Shirt/product-reviews/B0CHRSBWKP/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews"
page1<- prodDetails(link1)

link2 <- "https://www.amazon.co.uk/Levis-Original-Short-Sleeved-Housemark-T-Shirt/product-reviews/B0CHRSBWKP/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
page2<- prodDetails(link2)

link3 <- "https://www.amazon.co.uk/Levis-Original-Short-Sleeved-Housemark-T-Shirt/product-reviews/B0CHRSBWKP/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
page3<- prodDetails(link3)

ProdReview10 <- rbind(page1,page2,page3)

#view(ProdReview10)


```
Merging All 10 Products
```{r}
AllProducts <- rbind(ProdReview1,
                     ProdReview2,
                     ProdReview3,
                     ProdReview4,
                     ProdReview5,
                     ProdReview6,
                     ProdReview7,
                     ProdReview8,
                     ProdReview9,
                     ProdReview10
                     )
AllProducts
#view(AllProducts)
```